SELECT CONTEST_ID, HACKER_ID, NAME, SA, SB, SC, SD FROM (
    SELECT CT.CONTEST_ID, CT.HACKER_ID, CT.NAME, SUM(STS) SA, SUM(SAS) SB, SUM(STV) SC, SUM(SQV) SD
    FROM CONTESTS CT
    INNER JOIN COLLEGES CL ON (CT.CONTEST_ID = CL.CONTEST_ID)
    INNER JOIN CHALLENGES CG ON (CG.COLLEGE_ID = CL.COLLEGE_ID)
    LEFT OUTER JOIN 
    (
        SELECT CHALLENGE_ID, SUM(TOTAL_VIEWS) STV, SUM(TOTAL_UNIQUE_VIEWS) SQV
        FROM VIEW_STATS
        GROUP BY CHALLENGE_ID
    ) SUB1 ON (CG.CHALLENGE_ID = SUB1.CHALLENGE_ID)
    LEFT OUTER JOIN (
        SELECT CHALLENGE_ID, SUM(TOTAL_SUBMISSIONS) STS, SUM(TOTAL_ACCEPTED_SUBMISSIONS) SAS
        FROM SUBMISSION_STATS
        GROUP BY CHALLENGE_ID
    ) SUB2 ON (CG.CHALLENGE_ID = SUB2.CHALLENGE_ID)
    GROUP BY  CT.CONTEST_ID, CT.HACKER_ID, CT.NAME   
) TMP
WHERE (SA + SB+ SC + SD) > 0
ORDER BY CONTEST_ID