SELECT N, 'Root' FROM BST WHERE P IS NULL
UNION
SELECT N, 'Inner' FROM BST WHERE N  IN (SELECT P FROM BST) AND P IS NOT NULL
UNION 
SELECT N, 'Leaf' FROM (
SELECT N FROM BST EXCEPT SELECT P FROM BST) TMP